version: '3.8'
services:
  web:
    build: .
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://narrationbox:nb123@db:5432/nb_task_manager
    depends_on:
      - db
    restart: always
    networks:
      - app_network
  
  db:
    image: postgres:latest
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=narrationbox
      - POSTGRES_PASSWORD=nb123
      - POSTGRES_DB=nb_task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app_network
    restart: always

networks:
  app_network:

volumes:
  postgres_data:
